### ISSUE TITLE
need to force-push

### ISSUE THREAD

**Issue by hannesm** [mirage/ethernet#1]
I used `git filter-branch --subdirectory-filter src/ethif -- --all` to split out this repository from tcpip.

but ethif got moved around a bit, I'm now running `git filter-branch --tree-filter sh -c "find . ! -name eth\*.ml\* -delete" --prune-empty HEAD` which is likely to preserve more history. afterwards I'll cherry-pick commits from here onto the new HEAD, resulting in different commit ids.

the release and tag need to be re-done, but the tarball checksum shouldn't change ;)

will do this tonight, likely only @avsm and myself need to worry of his cloned repository

**Comment by avsm** [comment]
fine by me!

**Comment by hannesm** [comment]
done, unfortunately checksum changed... according to diffoscope the two tarballs are equal, but md5 has a different opinion (diff -ur of the extracted contents doesn't show any difference)
